# Generated by Django 5.2.4 on 2025-07-26 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_purchase_user_purchased_sweets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sweet',
            name='created_by',
        ),
    ]
